{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "from instrument import *\n",
    "from tkinter import *\n",
    "from consts import *\n",
    "import sounddevice as sd\n",
    "import numpy as np\n",
    "import mido\n",
    "import time \n",
    "\n",
    "\n",
    "colors = [\"blue\", \"red\", \"yellow\", \"pink\"]\n",
    "\n",
    "\n",
    "class MidiSequencerTkPLUS:\n",
    "    # análogo a lo anterior\n",
    "    def __init__(self,tk,instrument=None, midis=None):\n",
    "        self.instruments = instrument\n",
    "\n",
    "        #si se pasa un vector vacio se settea a un instrumento\n",
    "        if(len(instrument) == 0):\n",
    "            self.instruments.append(Instrument(tk,amp=0.2,ratio=3,beta=0.6))\n",
    "\n",
    "        c = 0\n",
    "        j = 0\n",
    "        # trato instrument com oun vector de instrumentos\n",
    "        for i in instrument:\n",
    "            self.instruments[j] = i\n",
    "\n",
    "            frame = LabelFrame(tk, text=\"Midi Sequencer\", bg=\"#908060\")\n",
    "            frame.pack(side=TOP)\n",
    "            frameFile = Frame(frame, highlightbackground=colors[c], highlightthickness=6)\n",
    "            \n",
    "            c += 1\n",
    "            if(c == len(colors)): \n",
    "                c = 0\n",
    "                \n",
    "            frameFile.pack(side=TOP)\n",
    "            Label(frameFile,text='Archivo MIDI: ').pack(side=LEFT)\n",
    "    \n",
    "            self.file = Entry(frameFile) #.pack(side=RIGHT)\n",
    "\n",
    "            if(j < len(midis)):\n",
    "                self.file.insert(14,midis[j])\n",
    "                print(midis[j])\n",
    "                self.file.pack(side=LEFT)\n",
    "\n",
    "            j += 1\n",
    "            \n",
    "\n",
    "            self.transport = 0\n",
    "            \n",
    "            self.text = Text(frame,height=6,width=23)\n",
    "            self.text.pack(side=RIGHT)\n",
    "            playBut = Button(frame,text=\"Play\", command=self.play)\n",
    "            playBut.pack(side=TOP)\n",
    "            #stopBut = Button(frame,text=\"Stop\", command=self.stop)\n",
    "            #stopBut.pack(side=BOTTOM)\n",
    "            \n",
    "\n",
    "        #########\n",
    "        self.tick = 1\n",
    "        self.state = 'off'\n",
    "        \n",
    "    # obtención de la secuencia midi (noteOn/Off) con tiempos relativos al inicio\n",
    "    def getSeq(self,midiEvents):\n",
    "        seq = []\n",
    "        accTime = 0\n",
    "        for m in midiEvents:\n",
    "            accTime += m.time\n",
    "            if m.type=='note_on':\n",
    "                if m.velocity==0: seq.append((accTime,'noteOff',m.note+self.transport,m.channel))\n",
    "                else: seq.append((accTime,'noteOn',m.note+self.transport,m.channel))    \n",
    "            elif m.type=='note_off':\n",
    "                seq.append((accTime,'noteOff',m.note+self.transport,m.channel))\n",
    "        return seq\n",
    "\n",
    "  \n",
    "    def play(self):\n",
    "        events = mido.MidiFile(self.file.get())\n",
    "        seq = self.getSeq(events)\n",
    "        print(seq)\n",
    "\n",
    "        self.state = 'on'\n",
    "        self.playLoop(seq)\n",
    "\n",
    "    def playLoop(self,seq,item=0,accTime=0):   \n",
    "        if item>=len(seq) or self.state =='off':\n",
    "            return\n",
    "\n",
    "        # ahora tenemos que procesar todos los ítems cuyo tiempo supere el crono accTime    \n",
    "        while item<len(seq) and accTime>=seq[item][0]:\n",
    "            (_,msg,midiNote,_chan) = seq[item]  # (time,'noteOff',midNote,channel)\n",
    "            self.text.insert('6.0',  f'{msg} {midiNote}\\n') \n",
    "            if msg=='noteOn':  \n",
    "                self.instrument.noteOn(midiNote)                   \n",
    "            else: # msg noteOff    \n",
    "                self.instrument.noteOff(midiNote)                   \n",
    "            item += 1 # y avanzmos ítem\n",
    "\n",
    "\n",
    "        # avanzammos crono \n",
    "        accTime += self.tick/1000\n",
    "\n",
    "        self.text.after(self.tick,lambda: self.playLoop(seq,item,accTime)) \n",
    "\n",
    "         \n",
    "    def stop(self):\n",
    "        self.instrument.stop()\n",
    "        self.state = 'off'  \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      "bumblebee.mid\n",
      "piratas.mid\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib\\tkinter\\__init__.py\", line 1967, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Temp\\ipykernel_19596\\1997435670.py\", line 78, in play\n",
      "    events = mido.MidiFile(self.file.get())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\ineso\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\mido\\midifiles\\midifiles.py\", line 319, in __init__\n",
      "    with open(filename, 'rb') as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'piratas.mid'\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "from midiSequencerTk import *\n",
    "import os    \n",
    "from instrument import *\n",
    "\n",
    "\n",
    "def test():\n",
    "    def callback(outdata, frames, time, status):    \n",
    "        if status: print(status)    \n",
    "        #print(inputs)\n",
    "        s = np.sum([i.next() for i in inputs],axis=0)\n",
    "        s = np.float32(s)\n",
    "        outdata[:] = s.reshape(-1, 1)\n",
    "\n",
    "    os.system('xset r off')\n",
    "    tk = Tk()\n",
    "\n",
    "    instrumentos = []\n",
    "    instrumentos.append(Instrument(tk, \"Holaaa\", 0.3, 4, 0.5))\n",
    "    instrumentos.append(Instrument(tk, \"Adiosss\", 0.1, 3, 0.7))\n",
    "    #instrumentos.append(Instrument(tk, \"Huh\"))\n",
    "\n",
    "    midis = [\"bumblebee.mid\", \"piratas.mid\"]\n",
    "\n",
    "    seq = MidiSequencerTkPLUS(tk,instrumentos, midis)\n",
    "    #print(seq.seq)\n",
    "    inputs = instrumentos\n",
    "\n",
    "    stream = sd.OutputStream(samplerate=SRATE, channels=1, blocksize=CHUNK, callback=callback)\n",
    "    stream.start()\n",
    "\n",
    "    tk.mainloop()\n",
    "\n",
    "    stream.close()\n",
    "    os.system('xset r on')\n",
    "\n",
    "test()\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
